[build]
  base = "blockvault-frontend"
  publish = "blockvault-frontend/build"
  command = "npm ci && npm run build"

[build.environment]
  # Set your production backend API URL here (or via Netlify UI > Site settings > Environment)
  # Example: "https://api.blockvault.example.com"
  REACT_APP_API_URL = ""

# SPA fallback so React Router routes work on refresh
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
